# Unbind the default prefix (Ctrl + B)
unbind C-b

# Set Ctrl + Space as the new prefix
# set -g prefix C-Space
# bind C-Space send-prefix

# Make split panes easier to use
bind | split-window -h  # Split pane horizontally
bind - split-window -v  # Split pane vertically

# Allow easy reloading of tmux configuration
bind R source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Enable mouse support (optional, but helpful)
set -g mouse on

# set mouse on with prefix m
bind m \
    set -g mouse on \;\
    display 'Mouse: ON'
# set mouse off with prefix M
bind M \
    set -g mouse off \;\
    display 'Mouse: OFF'  

# Set window renaming
set -g automatic-rename on

# Pane navigation shortcuts (using vim-style navigation)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-p previous-window
bind C-n next-window

bind C-[ previous-window
bind C-] next-window



bind c new-window -a -c "#{pane_current_path}"

set -g base-index 1
setw -g pane-base-index 1

set -g history-limit 50000
