FROM alpine
RUN apk add --no-cache git bash curl ncurses 
WORKDIR /root
ENTRYPOINT ["/bin/bash", "-c", "curl -Lks https://raw.githubusercontent.com/Bungogood/dotfiles/master/.dotfiles/install.sh | /bin/bash && /bin/bash"]
